version: "3.8"


services:
  db:
      image: postgres:14.2
      volumes:
        - db-data:/var/lib/postgresql/data
      restart: always
      env_file: .env.list
      environment:
        PGDATA: var/lib/postgresql/data
      ports:
        - "5432:5432"


  pgadmin:
    image: dpage/pgadmin4:6.8
    environment:
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
    env_file: .env.list
    ports:
      - "8080:80"
    links:
      - "db:pgsql-server"

volumes:
  db-data:
  pgadmin-data: